### ISSUE TITLE
Which software did you use for the UI mock-up?

### ISSUE THREAD

**Issue by damithc** [AY1920S1-CS2103T-T11-4/main#30]
Guys, your UI mock-up looks nice. Which software did you use to create it?
![image](https://user-images.githubusercontent.com/1673303/66263642-d74d1600-e828-11e9-9273-5f7752a52ddc.png)

**Comment by ang-zeyu** [comment]
Hi Prof, we used goodnotes on my ipad to make it haha 😄

**Comment by damithc** [comment]
Got it 👍
